sudo: false
language: erlang
otp_release:
  - 20.0
  - 19.3
  - 18.0
  - 17.0
before_script:
  - wget https://s3.amazonaws.com/rebar3-nightly/rebar3
  - chmod u+x rebar3
script: ./rebar3 compile && ./rebar3 eunit && ./rebar3 dialyzer
